export const FETCH_STATUS = {
  LOADING: 'LOADING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  UNKNOWN: 'UNKNOWN',
};

export const REQUEST_TYPE = {
  FETCH: 'FETCH',
  REFRESH: 'REFRESH',
  LOAD_MORE: 'LOAD_MORE',
  LOAD_PREV: 'LOAD_PREV',
};

export const DEFAULT_PAGE_SIZE = 10;
